### ISSUE TITLE
PF4 Figma kit audit and updates

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/pf-roadmap#105]
##Definition of done
```[tasklist]
- [ ] A complete audit of the v4 Figma library
- [ ] Updates to v5 for users migrating from Sketch
```

```[tasklist]
### Breakdown of the work to be done
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/651
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/652
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/653
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/656
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/655
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/654
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/650
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/649
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/648
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/647
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/646
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/645
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/644
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/643
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/642
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/641
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/640
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/639
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/638
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/637
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/636
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/635
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/634
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/633
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/632
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/631
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/630
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/629
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/628
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/627
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/626
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/625
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/624
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/623
```
