### ISSUE TITLE
Penta Design Kit in Figma

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/pf-roadmap#142]
## Definition of done
Completed design kit for the new Penta library in Figma
- [x] patternfly/patternfly-design-kit#659
- [x] patternfly/patternfly-design-kit#660
- [x] patternfly/patternfly-design-kit#661
- [x] patternfly/patternfly-design-kit#662
- [x] patternfly/patternfly-design-kit#663
- [x] patternfly/patternfly-design-kit#664
- [x] patternfly/patternfly-design-kit#665
- [x] patternfly/patternfly-design-kit#666
- [x] patternfly/patternfly-design-kit#667
- [x] patternfly/patternfly-design-kit#668
- [x] patternfly/patternfly-design-kit#669
- [x] patternfly/patternfly-design-kit#670
- [x] patternfly/patternfly-design-kit#671
- [x] patternfly/patternfly-design-kit#672
- [x] patternfly/patternfly-design-kit#673
- [x] patternfly/patternfly-design-kit#674
- [x] patternfly/patternfly-design-kit#675
- [x] patternfly/patternfly-design-kit#676
- [x] patternfly/patternfly-design-kit#677
- [x] patternfly/patternfly-design-kit#678
- [x] patternfly/patternfly-design-kit#679
- [x] patternfly/patternfly-design-kit#680
- [x] patternfly/patternfly-design-kit#681
- [x] patternfly/patternfly-design-kit#682
- [x] patternfly/patternfly-design-kit#683
- [x] patternfly/patternfly-design-kit#684
- [x] patternfly/patternfly-design-kit#685
- [x] patternfly/patternfly-design-kit#686
- [x] patternfly/patternfly-design-kit#687
- [x] patternfly/patternfly-design-kit#688
- [x] patternfly/patternfly-design-kit#689
- [x] patternfly/patternfly-design-kit#690
- [x] patternfly/patternfly-design-kit#691
