### ISSUE TITLE
Update PatternFly bugs, docs, demos & examples

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/pf-roadmap#144]
### Completing the following demos
- [ ] Empty state demos to include Design patterns for common use cases
- [x] https://github.com/patternfly/patternfly/issues/5613
- [x] https://github.com/patternfly/patternfly-org/issues/3751
- [x] https://github.com/patternfly/patternfly-org/issues/3733

**Comment by andrew-ronaldson** [comment]
##Definition of done
### Completing the following demos
- [ ] Empty state demos to include Design patterns for common use cases
