### ISSUE TITLE
Expose token documentation on workspaces

### ISSUE THREAD

**Issue by srambach** [patternfly/pf-roadmap#148]
Tokens will need to be documented on the workspaces and PatternFly.org. 

- [x] patternfly/patternfly-design#1273
- [x] patternfly/patternfly-org#3755
- [x] patternfly/patternfly-org#3756

**Comment by andrew-ronaldson** [comment]
Closed as complete
