### ISSUE TITLE
Checkpoint - React seed extension in Penta

### ISSUE THREAD

**Issue by srambach** [patternfly/pf-roadmap#152]
```[tasklist]
### Core issues
- [ ] https://github.com/patternfly/patternfly/issues/5710
- [ ] https://github.com/patternfly/patternfly/issues/5717
- [ ] https://github.com/patternfly/patternfly/issues/5706
- [ ] https://github.com/patternfly/patternfly/issues/5712
- [ ] https://github.com/patternfly/patternfly/issues/5713
- [ ] https://github.com/patternfly/patternfly/issues/5715
- [ ] https://github.com/patternfly/patternfly/issues/5728
- [ ] https://github.com/patternfly/patternfly/issues/5730
```

```[tasklist]
### React issues
- [ ] https://github.com/patternfly/patternfly-react/issues/9674
- [ ] https://github.com/patternfly/patternfly-react/issues/9675
- [ ] https://github.com/patternfly/patternfly-react/issues/9676
- [ ] https://github.com/patternfly/patternfly-react/issues/9677
- [ ] https://github.com/patternfly/patternfly-react/issues/9678
- [ ] https://github.com/patternfly/patternfly-react/issues/9679
- [ ] https://github.com/patternfly/patternfly-react/issues/9680
- [ ] https://github.com/patternfly/patternfly-react/issues/9681
```
