### ISSUE TITLE
Update topology to use Penta tokens

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/pf-roadmap#159]
```[tasklist]
### Tasks
- [x] Create a v6 branch of topology.
- [x] Pull in updates from core
- [x] Design updates to topology components
- [ ] Test with product teams
```
