### ISSUE TITLE
Extensions library: Penta design kit

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/pf-roadmap#164]
Building a separate Extensions Figma  library that consumes the Penta components library. The extensions library will deliver reusable assets for each extension and can grow to include broader patterns that can be found in the product ecosystem. Refer to UXD Hub for content ideas.

```[tasklist]
### Tasks
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/692
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/695
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/696
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/697
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/698
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/699
```

**Comment by lboehling** [comment]
do we need figma designs for react console https://www.patternfly.org/extensions/react-console ?
