### ISSUE TITLE
Penta: Tokenize Charts

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/pf-roadmap#175]
```[tasklist]
### Tasks
- [ ] https://github.com/patternfly/patternfly-design-kit/issues/709
- [ ] https://github.com/patternfly/patternfly/issues/5949
- [ ] https://github.com/patternfly/patternfly-react/issues/10121
```
