### ISSUE TITLE
Code mods: Preparing for v6

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/pf-roadmap#176]
```[tasklist]
### Tasks
- [ ] https://github.com/patternfly/pf-codemods/issues/601
- [ ] https://github.com/patternfly/pf-codemods/issues/598
- [ ] https://github.com/patternfly/pf-codemods/issues/595
- [ ] https://github.com/patternfly/pf-codemods/issues/594
- [ ] https://github.com/patternfly/pf-codemods/issues/593
- [ ] https://github.com/patternfly/pf-codemods/issues/573
- [ ] https://github.com/patternfly/pf-codemods/issues/564
```
