### ISSUE TITLE
Micro-animation round 2

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/pf-roadmap#184]
```[tasklist]
### Design work
- [ ] https://github.com/patternfly/patternfly-design/issues/1331
- [ ] https://github.com/patternfly/patternfly-design/issues/1326
- [ ] https://github.com/patternfly/patternfly-design/issues/1325
- [ ] https://github.com/patternfly/patternfly-design/issues/1327
- [ ] https://github.com/patternfly/patternfly-design/issues/1330 
```
```[tasklist]
### Core work
- [ ] https://github.com/patternfly/patternfly/issues/6959
- [ ] https://github.com/patternfly/patternfly/issues/6597
- [ ] https://github.com/patternfly/patternfly/issues/6601
- [ ] https://github.com/patternfly/patternfly/issues/6603
- [ ] https://github.com/patternfly/patternfly/issues/6591
- [ ] https://github.com/patternfly/patternfly/issues/6812
- [ ] https://github.com/patternfly/patternfly/issues/7151
```
```[tasklist]
### React work
- [ ] https://github.com/patternfly/patternfly-react/issues/10440
```

**Comment by andrew-ronaldson** [comment]
Closing. Refactored in Initiative
