### ISSUE TITLE
Navigation: Docked navigation variant

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/pf-roadmap#188]
```[tasklist]
### Workflow
- [ ] Using our PoC and ChatBot extension, create a tool to generate code samples for consumers
- [ ] Training models such as Granite to assist with PatternFly v6 migration
- [ ] Train models on PatternFly documentation to address community questions.
```
