### ISSUE TITLE
Onboarding documentation

### ISSUE THREAD

**Issue by kmcfaul** [patternfly/pf-roadmap#226]
Documentation catered towards UXD devs ramping up on various PF repos. See planning topics for template.

- [ ] patternfly/patternfly-react#11310

- [ ] #229

- [ ] Chatbot

- [ ] React component groups

- [ ] patternfly/patternfly-design#1361

- [ ] Topology

- [ ] Org (eventually, post-revamp)

- [ ] Quickstarts

- [x] patternfly/patternfly-react#11324

Extensions onboarding may be able to be combined into a single document depending on the length.
Product onboarding documentation should be tracked in JIRA.

---

**Jira Issue:** [PF-1235](https://redhat.atlassian.net/browse/PF-1235)
