### ISSUE TITLE
Penta theming beta

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/pf-roadmap#38]
*Design issues*
- [ ] [Create documentation for the Penta theme](https://github.com/patternfly/patternfly-design/issues/1177)
- [ ] [Create updated design library](https://github.com/patternfly/patternfly-design/issues/1130)
- [ ] [Design token documentation](https://github.com/patternfly/patternfly-design/issues/1258)
- [ ] Consider Penta theme for topology
- [ ] Consider Penta theme for Charts

*Core issues*
- [ ] [[Epic] CSS Variable theming for v5#5413](https://github.com/patternfly/patternfly/issues/5413)
- [ ] POC of theming with Penta theme in a few components/page demo
- [ ] [Epic] Implement theming changes across all components

*React issues*
- [ ] POC of theming with Penta theme in a demo (consume core theming)
- [ ] [Epic] Consume theming changes in React repo
- [ ] Consume Penta theme in Charts

*Org/workspaces issues*
- [ ] [Epic] Consume theming changes in org
- [ ] Allow for switching between themes (including dark versions) on workspaces
- [ ] Build a style dictionary
- [ ] Link style dictionary to CSS variables
- [ ] Link style dictionary to Sketch design library
- [ ] Link style dictionary to org documentation of tokens

*Extensions*
- [ ] [Epic] Consume theming changes in extensions
- [ ] Consume Penta theme in topology

Definition of done:
*Implementation*
Tokens are used in the Sketch library
Tokens used in Core
Tokenized theme core styles are properly consumed in React
Website uses tokens as much as possible for any necessary customizations
Classic and Penta themes both implemented
	
*Theme switching*
Workspaces have the capability to switch between themes
Website and workspaces use tokens with Penta theme, switchable to Classic theme, dark themes
User’s global light/dark preference is respected

*Style Dictionary*
Style dictionary exists and is linked to Sketch/Figma and Core as the gold source. 
Website documentation may also pull directly from the style dictionary instead of pulling from the core variables.

*Documentation*
Token documentation is on website
Penta design guidelines are on website (including updated graphics)
Code mods/upgrade guide available to consumers

**Comment by andrew-ronaldson** [comment]
<img width="1725" alt="Screenshot 2023-04-27 at 11 03 21 PM" src="https://user-images.githubusercontent.com/28658548/235036893-0aea60a2-9a69-4297-acbe-8f7cf2d771c1.png">

**Comment by andrew-ronaldson** [comment]
Closing this issue. It has been broken up into various Epics
