### ISSUE TITLE
Harden & deliver dark theme

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/pf-roadmap#39]
in core:
- [x] patternfly/patternfly#5523

> - [ ] Custom colors
> - [ ] Inline alert https://github.com/patternfly/patternfly/issues/5501
> - [ ] Horizontal nav
> - [ ] Alert - info variant contrast (2 different blues)
> - [ ] Banner - modifier names need to be updated (danger vs red etc)
> - [ ] Brand - fix brand image not to hard code the fill color and/or add dark/light version. Also visible in card examples
> - [ ] Breadcrumb divider - adjust color (should be resolved by updating static icon color, existing issue)
> - [ ] Selectable/clickable cards need dark theme overrides
> - [ ] Code editor readonly version - Monaco editor has its own styling for dark theme so this is different in react. Address the gray border indicating read only
> - [ ] Drag and drop drag state/disabled state
> - [ ] Dual list contrast in the disabled state/disabled controls - update to more legible disabled item, but leave the control as the existing plain disabled action
> - [ ] Menu toggle split disabled state and icon are the same color
> - [ ] Application launcher hover state color
> - [ ] Application launcher favorites background color behind icons
> - [ ] Disabled states in general have some inconsistencies (dual list, tabs, ?)
> - [ ] Search highlighting - highlight color needs to be chosen for dark theme

~~core followup:~~
~~- [ ] Update dark theme stylesheets to use theme-able variables rather than hardcoded variables~~

in org:
- [x] https://github.com/patternfly/patternfly-org/issues/3372
  - above issue will include updating styles and overrides in org to consume dark theme 
- [x] patternfly/patternfly-org#3514
- [ ] Implement ability to swap out images when website switched to dark theme (nice to have)
- [ ] Update images (community page, design guidelines, etc) to include a dark theme version (nice to have)

in extensions:

- [x] patternfly/react-topology#49
- [x] patternfly/patternfly-extension-issues#50
- [ ] Address outstanding dark theme issues identified during audit
