### ISSUE TITLE
Update extensions to v5

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/pf-roadmap#46]
```[tasklist]
### Tasks
- [ ] https://github.com/patternfly/patternfly-quickstarts/issues/248
- [ ] https://github.com/patternfly/react-topology/issues/55
- [ ] https://github.com/patternfly/react-log-viewer/issues/30
- [ ] https://github.com/patternfly/react-console/issues/37
- [ ] https://github.com/patternfly/react-user-feedback/issues/56
- [ ] https://github.com/patternfly/react-catalog-view/issues/43
```
