### ISSUE TITLE
v5 example/demo clean up (possibly post v5)

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/pf-roadmap#48]
This work is clean up work for examples and demos on the website.

In a crunch it can be completed after v5 is released, it just means our examples and demos will be outdated or buggy on patternfly.org when v5 goes live. It can be updated as a next priority soon after.

```[tasklist]
### High priority
- [ ] https://github.com/patternfly/patternfly-react/issues/9015
- [ ] https://github.com/patternfly/patternfly-org/issues/3489
- [ ] https://github.com/patternfly/patternfly-react/issues/9144
- [ ] https://github.com/patternfly/patternfly-react/issues/9003
- [ ] https://github.com/patternfly/patternfly-react/issues/8921
- [ ] https://github.com/patternfly/patternfly/issues/5566
- [ ] https://github.com/patternfly/patternfly/issues/5557
- [ ] https://github.com/patternfly/patternfly-react/issues/9018
- [ ] https://github.com/patternfly/patternfly-react/issues/9179
- [ ] https://github.com/patternfly/patternfly-react/issues/9180
- [ ] https://github.com/patternfly/patternfly/issues/5613
- [ ] https://github.com/patternfly/patternfly/issues/5614
```

```[tasklist]
### Nice to have
- [ ] https://github.com/patternfly/patternfly-react/issues/9038
- [ ] https://github.com/patternfly/patternfly-react/issues/9100
- [ ] https://github.com/patternfly/patternfly-org/issues/3525
- [ ] https://github.com/patternfly/patternfly-org/issues/3534 
```
