### ISSUE TITLE
Complete initial implementation of global tokens

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/pf-roadmap#56]
This should build on the work done in https://github.com/patternfly/patternfly/pull/5482

Definition of done
- [x] Core global variables are updated to match tokens shared with the design kit.
- [x] Components using global variables are updated with new tokens.

```[tasklist]
### Tasks
- [ ] https://github.com/patternfly/patternfly/issues/5671
```

**Comment by andrew-ronaldson** [comment]
Closed with issue [5671](https://github.com/patternfly/patternfly/issues/5671)
