### ISSUE TITLE
Core: Build out initial Penta components

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/pf-roadmap#58]
Checklist for tokenizing each component:
- Move component variables to be scoped to ADD `:where(:root),` along with the component scope within a :where(). 
```
:where(:root),
:where(.#{$toolbar}) {
```

- Only tokens should be used to set values of component variables
- In most cases, a semantic token should be used over a base token
- If there isn't a semantic token for the value, note it and let design know
- If a token is used within a style, a component variable should be created and set instead
- Remove the old dark theme adjustment and the dark theme stylesheet along with the themes folder, which would now be empty

Test:
- Verify component against [Figma designs](https://www.figma.com/file/VMEX8Xg2nzhBX8rfBx53jp/Penta-Component-Library?type=design&node-id=0%3A1&mode=design&t=UYdtnJ3iLAxCv52d-1). Token values originate in the [tokens and styles library](https://www.figma.com/file/iPks6qJfvvwGOTHgpoIvHm/Penta-Design-Tokens-%26-Styles-Library?type=design&node-id=83%3A280&mode=design&t=f9J1W4wVsfCfdvek-1)
- Make sure that dark theme looks correct
- Make sure that RTL still works properly
- Check responsive behavior
- Check Axe, especially for color contrast problems
- Design should give a 👍

```[tasklist]
### Components (grouped)
- [ ] https://github.com/patternfly/patternfly/issues/5851
- [ ] https://github.com/patternfly/patternfly/issues/5706
- [ ] https://github.com/patternfly/patternfly/issues/5707
- [ ] https://github.com/patternfly/patternfly/issues/5710
- [ ] https://github.com/patternfly/patternfly/issues/5711
- [ ] https://github.com/patternfly/patternfly/issues/5712
- [ ] https://github.com/patternfly/patternfly/issues/5713
- [ ] https://github.com/patternfly/patternfly/issues/5714
- [ ] https://github.com/patternfly/patternfly/issues/5715
- [ ] https://github.com/patternfly/patternfly/issues/5716
- [ ] https://github.com/patternfly/patternfly/issues/5717
- [ ] https://github.com/patternfly/patternfly/issues/5718
- [ ] https://github.com/patternfly/patternfly/issues/5719
- [ ] https://github.com/patternfly/patternfly/issues/5723
- [ ] https://github.com/patternfly/patternfly/issues/5724
- [ ] https://github.com/patternfly/patternfly/issues/5725
- [ ] https://github.com/patternfly/patternfly/issues/5726
- [ ] https://github.com/patternfly/patternfly/issues/5727
- [ ] https://github.com/patternfly/patternfly/issues/5728
- [ ] https://github.com/patternfly/patternfly/issues/5729
- [ ] https://github.com/patternfly/patternfly/issues/5730
- [ ] https://github.com/patternfly/patternfly/issues/5731
- [ ] https://github.com/patternfly/patternfly/issues/5732
- [ ] https://github.com/patternfly/patternfly/issues/5733
- [ ] https://github.com/patternfly/patternfly/issues/5734
- [ ] https://github.com/patternfly/patternfly/issues/5735
- [ ] https://github.com/patternfly/patternfly/issues/5736
- [ ] https://github.com/patternfly/patternfly/issues/5737
- [ ] https://github.com/patternfly/patternfly/issues/5738
- [ ] https://github.com/patternfly/patternfly/issues/5739
- [ ] https://github.com/patternfly/patternfly/issues/5740
- [ ] https://github.com/patternfly/patternfly/issues/5741
- [ ] https://github.com/patternfly/patternfly/issues/5742
- [ ] https://github.com/patternfly/patternfly/issues/5743
- [ ] https://github.com/patternfly/patternfly/issues/5949
- [ ] https://github.com/patternfly/patternfly/issues/6235
- [ ] https://github.com/patternfly/patternfly/issues/6259
```
