### ISSUE TITLE
Style library/dictionary

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/pf-roadmap#60]
```[tasklist]
### Definition of done
- [x] Tokens are built into a gold source file (likely JSON format)
- [x] A style dictionary such as [Style Dictionary](https://amzn.github.io/style-dictionary/#/) connects the design kit to core code
- [x] Design tokens are documented on the PatternFly website
```
Note: for last item above, an issue has been created to automate sychronization of tokens to core.
https://github.com/patternfly/design-tokens/issues/39

```[tasklist]
### Tasks
- [ ] https://github.com/patternfly/patternfly-design/issues/1258
- [ ] https://github.com/patternfly/patternfly/issues/5946
```

```[tasklist]
### Tasks
- [ ] https://github.com/patternfly/design-tokens/issues/1
- [ ] https://github.com/patternfly/design-tokens/issues/2
- [ ] https://github.com/patternfly/design-tokens/issues/3
```

**Comment by andrew-ronaldson** [comment]
Closed issue and create a follow up for [enhancements](https://github.com/patternfly/design-tokens/issues/39)
