### ISSUE TITLE
Write Penta documentation/website

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/pf-roadmap#63]
```[tasklist]
### Tasks
- [ ] https://github.com/patternfly/patternfly-org/issues/3756
- [ ] https://github.com/patternfly/patternfly-org/issues/3890
- [ ] https://github.com/patternfly/patternfly-org/issues/3877
```
